# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'New-Instagram' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for New-Instagram
    pod 'Parse'
    pod 'Toucan'
    pod 'ParseUI'
    
  target 'New-InstagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'New-InstagramUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
